#!/usr/bin/python

import os
import sys
import thread
import commands
import glob

from threading import Thread
from optparse import OptionParser

parser = OptionParser(description="\
Very useful script for keeping your Git repos in `~/Projects` clean and up-to-date. \
Looks for Git repositories and runs commands effectively (in parallel).")

parser.add_option('-v', '--verbose',
                  action='store_true',
                  default=False,
                  )
(options, args) = parser.parse_args()

class thread_it(Thread):
    def __init__ (self,param):
        Thread.__init__(self)
        self.param = param
    def run(self):

        try:
          if os.path.exists(os.path.join(self.param, '.git')):
            out = commands.getoutput('cd '+ str(self.param) + '; git status')

            lock.acquire()
            output.append(out)
            if 'nothing to commit, working directory clean' in out:
              sys.stdout.write('.')
            else:
              if options.verbose:
                sys.stdout.write('\x1b[;31mDIRTY('+ str(self.param) + ')\x1b[0m')
              else:
                sys.stdout.write('\x1b[;31m!\x1b[0m')
            sys.stdout.flush()
            lock.release()
        except:
          pass

threads = []
output = []
lock = thread.allocate_lock()

for j in glob.glob( os.path.join(os.path.abspath('./'), '*') ):
    current = thread_it(j)
    threads.append(current)
    current.start()

for t in threads:
    t.join()

print output
